name: wr_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  dio: ^4.0.4
  shared_preferences: ^2.0.10
  cached_network_image: ^3.2.0
  flutter_screenutil: ^5.0.0+2
  flutter_swiper_plus: ^2.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

